project:
  type: website
  output-dir: docs

website:
  title: "Akbar Rakha Syahpradana"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rsyahpradana
format:
  html:
    theme: flatly
    css: styles.css



